\c dog_dev
CREATE TABLE food_table(
   food_name   VARCHAR(20) NOT NULL
  ,edible      VARCHAR(7) NOT NULL
  ,description TEXT NOT NULL
);
INSERT INTO food_table(food_name,edible,description) VALUES ('potato','yes',E'Potatoes are safe for dogs when cooked and unseasoned. Never feed your dog raw potato and be aware that salt, onion, and garlic can upset your pup’s stomach.');
INSERT INTO food_table(food_name,edible,description) VALUES ('avocado','no',E'Avocados contain persin in their fruit, leaves, pits, bark and skin. Dogs are allergic and will exhibit symptoms of vomiting and diarrea.  While small amounts aren''t typically fatal, it''s smart to contact your vet as large amounts of avocado consumption can cause mastitis, heart failure, and death');
INSERT INTO food_table(food_name,edible,description) VALUES ('popcorn','caution',E'Plain, air-popped popcorn makes a nice occasional treat for your dog. But, kernels can get stuck in dogs’ teeth and pose a choking hazard, so it is probably a good idea to keep whole or only partially popped kernels away');
INSERT INTO food_table(food_name,edible,description) VALUES ('macadamia nuts','no',E'Macadamia nuts can cause weakness, depression, vomiting, tremors and hyperthermia in dogs. Signs usually appear within 12 hours of ingestion and can last approximately 12 to 48 hours.');
INSERT INTO food_table(food_name,edible,description) VALUES ('xylitol','no',E'Xylitol is used as a sweetener in many products, including gum, candy, baked goods and toothpaste. It can cause insulin release in most species, which can lead to liver failure. The increase in insulin leads to hypoglycemia (lowered sugar levels). Initial signs of toxicosis include vomiting, lethargy and loss of coordination. Signs can progress to seizures. Elevated liver enzymes and liver failure can be seen within a few days.');
INSERT INTO food_table(food_name,edible,description) VALUES ('apples','yes',E'Apples are an excellent source of vitamins A and C, as well as fiber for your dog. They are low in protein and fat, making them the perfect snack for senior dogs. Just be sure to remove the seeds and core first. Try them frozen for an icy warm weather snack.');
INSERT INTO food_table(food_name,edible,description) VALUES ('bananas','yes',E'In moderation, bananas are a great low-calorie treat for dogs. They’re high in potassium, vitamins, biotin, fiber, and copper. They are low in cholesterol and sodium, but because of their high sugar content, bananas should be given as a treat, not part of your dog’s regular diet.');
INSERT INTO food_table(food_name,edible,description) VALUES ('blueberries','yes',E'Blueberries are a superfood rich in antioxidants, which prevent cell damage in humans and canines alike. They’re packed with fiber and phytochemicals as well. ');
INSERT INTO food_table(food_name,edible,description) VALUES ('cherries','no',E'With the exception of the fleshy part around the seed, cherry plants contain cyanide and are toxic to dogs. Cyanide disrupts cellular oxygen transport, which means that your dog’s blood cells can’t get enough oxygen. If your dog eats cherries, be on the lookout for dilated pupils, difficulty breathing, and red gums, as these may be signs of cyanide poisoning.');
INSERT INTO food_table(food_name,edible,description) VALUES ('grapes','no',E'Grapes and raisins have both proved to be very toxic for dogs no matter the dog’s breed, sex, or age. In fact, grapes are so toxic that they can lead to acute sudden kidney failure. ');
INSERT INTO food_table(food_name,edible,description) VALUES ('raisins','no',E'Grapes and raisins have both proved to be very toxic for dogs no matter the dog’s breed, sex, or age. In fact, grapes are so toxic that they can lead to acute sudden kidney failure. ');
INSERT INTO food_table(food_name,edible,description) VALUES ('mushrooms','no',E'Wild mushrooms can be toxic for dogs. While only 50 to 100 of the 50,000 mushroom species worldwide are known to be toxic, the ones that are can really hurt your dog or even lead to death. Washed mushrooms from the supermarket could be OK, but it’s better to be safe than sorry; skip out on the fungi all together');
INSERT INTO food_table(food_name,edible,description) VALUES ('tomatoes','no',E'While the ripened fruit of the tomato plant (the red part humans normally eat) is generally considered safe for dogs, the green parts of the plant contain a toxic substance called solanine. While a dog would need to eat a large amount for it to make him or her sick, it’s better to skip tomatoes all together just to be safe.');
-- INSERT INTO food_table(food_name,edible,description) VALUES ('','',E'');
-- INSERT INTO food_table(food_name,edible,description) VALUES ('','',E'');
-- INSERT INTO food_table(food_name,edible,description) VALUES ('','',E'');
